Bug fixes
MonicaStoyanova/who-wants-to-be-a-millionaire pull request #19
Opened 2024-01-16 13:48 UTC by MonicaStoyanova

2024-01-19 10:20 UTC, Georgi07 requested changes

2024-01-19 10:20 UTC, Georgi07 commented on src/pages/GameOver/GameOver.js
You have a warning on line 55. You should compate "currentQuestionIndex" and "position" with "===" instead of "=="

2024-01-19 10:20 UTC, Georgi07 commented on src/components/Jokers/Audience/AudienceHelpJoker.js
There is a warning again. "Chart" is defined but never used

2024-01-19 10:20 UTC, Georgi07 commented on src/store/Slices/gamePlaySlice.js
For jokers name state variables "used" properly as we discussed. Boolean variables should start with "is/are"

2024-01-19 12:26 UTC, Georgi07 commented on src/components/Timer/Timer.module.css
> +  padding: 1.3em;
Export the properties as reusable classname in assets

2024-02-16 14:10 UTC, MonicaStoyanova commented on src/pages/GameOver/GameOver.js
fixed

2024-02-16 14:10 UTC, MonicaStoyanova commented on src/components/Jokers/Audience/AudienceHelpJoker.js
This import is needed for the chart to work properly, as per the documentation.

2024-02-16 14:18 UTC, merged